<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\..\extension\unity\Package\Runtime\Core\Diagnostics\RuntimeDiagnostic.cs" Link="Diagnostics\RuntimeDiagnostic.cs" />
    <Compile Include="..\..\extension\unity\Package\Runtime\Core\Klib\KlibModels.cs" Link="Klib\KlibModels.cs" />
    <Compile Include="..\..\extension\unity\Package\Runtime\Core\Klib\KlibModuleLoader.cs" Link="Klib\KlibModuleLoader.cs" />
  </ItemGroup>

</Project>
